// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojhquzvtkdpgcokezirb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qaHF1enZ0a2RwZ2Nva2V6aXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzODM1NzYsImV4cCI6MjA2Nzk1OTU3Nn0.Hj-eDsURWAa9sr4ndyj3KbbR7gAN27nl7KD-gzI6aA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});